apiVersion: v1
kind: Service
metadata:
  name: gear01
  namespace: gearman-dev-01
spec:
  selector:
    app: gearman-01
  ports:
    - protocol: TCP
      port: 4730
      targetPort: 4730
  type: ClusterIP 