apiVersion: v1
kind: Pod
metadata:
  name:   php-gearman
  namespace: gearman-dev-01
  labels:
    app: php-gearman-01

spec:
  containers:
    #- image: wsimmonds/jenkins-kubernetes:2.8
    - image: edusca/docker-php-gearman-extension
    #- image: csanchez/jenkins-kubernetes:0.11
      name: php-gearman-01